#!/bin/bash

#SBATCH -n40 -N16 #Number of cores and nodes
#SBATCH --ntasks-per-node=40
#SBATCH -p general --time=24:00:00
## OMP_NUM_THREADS controls the number of threads your application use
## This variable cat be set by the following command :

#ulimit -s unlimited
module load gcc
module load openmpi
module load cmake
module load mkl
export NSLOTS=64

#source /projects/opt/intel/parallel_studio_xe_2016/mkl/bin/mklvars.sh intel64
export OMP_NUM_THREADS=-1
#export KMP_STACKSIZE=3200M


## Copy files to work directory:
#cp $SUBMITDIR/YourDatafile $SCRATCH

## Mark outfiles for automatic copying to $SUBMITDIR:
#chkfile YourOutputfile

## Run command
mpirun -np 1 --map-by node $HOME/qmd-progress/build/gpmdcov input.in | tee out 
