#!/bin/bash
#SBATCH -n 20 #Number of cores 

#SBATCH --ntasks-per-node=40
#
#SBATCH -p ccs6 --time=168:00:00
## OMP_NUM_THREADS controls the number of threads your application use
## This variable cat be set by the following command :

ulimit -s unlimited
module load intel/13.1.2 mkl/11.3 cmake/3.3.2
source /projects/opt/intel/parallel_studio_xe_2016/mkl/bin/mklvars.sh intel64
#setenv OMP_NUM_THREADS 40
export OMP_NUM_THREADS=40
#export OMP_STACKSIZE=3.2g
export KMP_STACKSIZE=3200M


## Copy files to work directory:
#cp $SUBMITDIR/YourDatafile $SCRATCH

## Mark outfiles for automatic copying to $SUBMITDIR:
#chkfile YourOutputfile



## Run command
../builb/main | tee out 
