#!/bin/bash

#This script will compute the dihedral angle for a trajectory
#file in pdb or xy format.

RUN=$HOME/qmd-progress/build/getdihedral  #Program to get the dihedral angle.
FREQ=2010  #Frequency in line numbers to determine the bigining and end of the coordinates.
MAXLINES=44220 #Max number of lines of the file.
INIT=$FREQ #Initial line to start analysing the trajectory.
FILE="traj.pdb" #Filename.
INDEXES="53 47 51 46" #Atom indexes"

for (( i=$INIT; i<=$MAXLINES; i = i + $FREQ ))
do
echo $i
head -$i $FILE | tail -$FREQ > tmp.pdb
$RUN tmp.pdb $INDEXES
done
