#!/bin/bash

filename=$1
label=$2
label=$label")"

echo $filename
rm $filename".jpg"

convert -rotate "0" -density 400 -set units PixelsPerInch $filename plot.jpg

filename=`sed "s/.ps//g" <<< $filename`

convert -pointsize 150 -trim  -quality 10000 plot.jpg  label:$label +swap \
-append -pointsize 702 $filename".jpg"

rm plot.jpg 
